SCR_Faction {
 FactionKey "Tyn_RNRF"
 FactionColor 0.7789 0.5528 0.0107 1
 UIInfo UIInfo "{663515AB30E872F7}" {
  Name "#TYN-Faction_RNRF"
  Icon "{6A33922D2B950A7A}UI/Textures/Editor/EditableEntities/Factions/RNRF_Icon.edds"
 }
 "Identity of soldiers" FactionIdentity "{663515AB670569B8}" : "{66B977FEA8A304C8}Configs/Identities/FactionIdentity_RNRF.conf" {
 }
 m_iOrder 1000
 m_OutlineFactionColor 0.076 0.053 0 1
 m_NotificationFactionColor 0.658 0.461 0.009 1
 m_NotificationTextFactionColor 0.509 0.357 0.008 1
 m_sFactionFlag "{604E55530B6AD933}UI/Textures/Flags/RNRF_Flag.edds"
 m_FactionFlagMaterial "{55B362958FE3D8B5}Assets/Props/Fabric/Flags/Data/Flag_1_2_RNRF.emat"
 m_FactionLabel FACTION_Tyn_RNRF
 m_CallsignInfo SCR_FactionCallsignInfo "{663515ABB6F2D197}" : "{958043CE1648EC43}Configs/Callsigns/Callsigns_USSR.conf" {
 }
 m_sFactionRadioEncryptionKey "Pelmeshki"
 m_iFactionRadioFrequency 40000
 m_aRanks {
  SCR_CharacterRank "{663515AB88C95CA3}" {
   m_sRankName "#AR-Rank_WestPrivate"
   m_sRankNameUpper "#AR-Rank_WestPrivate-UC"
   m_sRankNameShort "#AR-Rank_WestPrivateShort"
   m_sInsignia "AR_Rank_OR-2"
  }
  SCR_CharacterRank "{663515AB8893C28E}" {
   m_iRank CORPORAL
   m_sRankName "#AR-Rank_WestCorporal"
   m_sRankNameUpper "#AR-Rank_WestCorporal-UC"
   m_sRankNameShort "#AR-Rank_WestCorporalShort"
   m_sInsignia "AR_Rank_OR-4_C"
  }
  SCR_CharacterRank "{663515AB8876560D}" {
   m_iRank SERGEANT
   m_sRankName "#AR-Rank_WestSergeant"
   m_sRankNameUpper "#AR-Rank_WestSergeant-UC"
   m_sRankNameShort "#AR-Rank_WestSergeantShort"
   m_sInsignia "AR_Rank_OR-5"
  }
  SCR_CharacterRank "{663515AB886822AD}" {
   m_iRank LIEUTENANT
   m_sRankName "#AR-Rank_WestLieutenant"
   m_sRankNameUpper "#AR-Rank_WestLieutenant-UC"
   m_sRankNameShort "#AR-Rank_WestLieutenantShort"
   m_sInsignia "AR_Rank_OF-1_1st"
  }
  SCR_CharacterRank "{663515AB884C041F}" {
   m_iRank CAPTAIN
   m_sRankName "#AR-Rank_WestCaptain"
   m_sRankNameUpper "#AR-Rank_WestCaptain-UC"
   m_sRankNameShort "#AR-Rank_WestCaptainShort"
   m_sInsignia "AR_Rank_OF-2"
  }
  SCR_CharacterRank "{663515AB882E0DBE}" {
   m_iRank MAJOR
   m_sRankName "#AR-Rank_WestMajor"
   m_sRankNameUpper "#AR-Rank_WestMajor-UC"
   m_sRankNameShort "#AR-Rank_WestMajorShort"
   m_sInsignia "AR_Rank_OF-3"
  }
  SCR_CharacterRank "{663515AB88003569}" {
   m_iRank RENEGADE
   m_sRankName "#AR-Rank_Renegade"
   m_sRankNameUpper "#AR-Rank_Renegade-UC"
  }
 }
 m_sGroupFlagsImageSet "{7CD99D22C7AE8195}UI/Textures/GroupManagement/FlagIcons/GroupFlagsOpfor.imageset"
 m_sGroupFlagsImageSetOutlines "{B9356E7B2E974DCD}UI/Textures/GroupManagement/FlagIcons/GroupFlagsOpfor-outline.imageset"
 m_aFlagNames {
  "infantry"
  "amphibious"
  "anti-air"
  "anti-air-artilery"
  "anti-armor-motorized"
  "antiarmor"
  "armored"
  "artillery"
  "combined"
  "helicopter"
  "helicopter-attack"
  "infantry-air"
  "machinegun"
  "maintenance"
  "medical"
  "mortar"
  "motorized"
  "motorized-infantry"
  "recon"
  "recon-motorized"
  "signal"
  "sniper"
  "supply-motorized"
  "undefined"
 }
 m_FactionHomeTerritoryConfig SCR_FactionHomeTerritoryConfig "{663515AA203A5162}" : "{5FE6C7E7968DA7A6}Configs/Identities/Territories/FactionHomeTerritory_RNRF.conf" {
 }
}