StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60D69CEAC1E9BFB9}" {
   Id "DRG-AT_SSO"
   Target_en_us "Scout anti-tank"
   Target_ru_ru "Разведчик-гранатомётчик"
   Target_uk_ua "Розвідник-гранатометник"
   Modified 1624681510
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{604B22650FBF60AB}" {
   Id "DRG-Automatic_rifleman_assistant"
   Target_en_us "Assistant Automatic Rifleman"
   Target_ru_ru "Помощник пулемётчика"
   Target_uk_ua "Помічник кулеметника"
   Modified 1697852040
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{6048E3A3C7FC0B33}" {
   Id "DRG-Automatic_rifleman_RPK"
   Target_en_us "Automatic rifleman"
   Target_ru_ru "Пулемётчик РПК"
   Target_uk_ua "Кулеметник РПК"
   Modified 1697855311
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{60D6C02F2C2C3EEC}" {
   Id "DRG-Commander_SSO"
   Target_en_us "Spec-Ops Commander"
   Target_ru_ru "Командующий ССО"
   Target_uk_ua "Командуючий ССО"
   Modified 1697852050
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{604744B0A9F4D6F3}" {
   Id "DRG-COMPANY_LEADER"
   Target_en_us "Company Leader"
   Target_ru_ru "Командир роты"
   Target_uk_ua "Командир роти"
   Modified 1615283655
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6048E3AB987DEBB7}" {
   Id "DRG-Description_HeaderCDF"
   Target_en_us "Tasks for CDF"
   Target_ru_ru "Задачи для ЧСО"
   Target_uk_ua "Задачі для ЧСО"
   Modified 1697852061
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{628699D4A6720E10}" {
   Id "DRG-Description_HeaderION"
   Target_en_us "Tasks for ION"
   Target_ru_ru "Задачи для ИОН"
   Target_uk_ua "Задачі для ION"
   Modified 1697854384
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{6048E3AB7E2BE2B7}" {
   Id "DRG-Description_HeaderRUS"
   Target_en_us "Tasks for AFRF"
   Target_ru_ru "Задачи для ВС РФ"
   Target_uk_ua "Задачі для ЗС РФ"
   Modified 1697852085
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{60477B7A1CFA3768}" {
   Id "DRG-DRIVER"
   Target_en_us "Crew-driver"
   Target_ru_ru "Механик-водитель"
   Target_uk_ua "Механік-водій"
   Modified 1640948359
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64D476D34F74E430}" {
   Id "DRG-Faction_IGF"
   Target_en_us "IGF"
   Target_ru_ru "НБФ"
   Target_uk_ua "НБФ"
   Modified 1691659230
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652ABD173A2C6FE5}" {
   Id "DRG-Flamethrower_SSO"
   Target_en_us "Spec-Ops -Flamethrower"
   Target_ru_ru "Оператор огнемётчик"
   Target_uk_ua "Оператор вогнемета"
   Modified 1697852121
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{60477B7AA35CC11C}" {
   Id "DRG-GUNNER"
   Target_en_us "Crew-Gunner"
   Target_ru_ru "Наводчик-оператор"
   Target_uk_ua "Навідник-оператор"
   Modified 1640948325
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{65312813CBC769CE}" {
   Id "DRG-Marksman_SSO"
   Target_en_us "Spec-Ops Sniper"
   Target_ru_ru "Оперативник снайпер"
   Target_uk_ua "Снайпер ССО"
   Modified 1697852218
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{60D6C02FD69A7C32}" {
   Id "DRG-Medic_SSO"
   Target_en_us "Spec-Ops Medic"
   Target_ru_ru "Оператор-медик ССО"
   Target_uk_ua "Бойовий медик ССО"
   Modified 1697852265
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{60D69CE9F9892157}" {
   Id "DRG-MG_SSO"
   Target_en_us "Spec-Ops Machinegunner"
   Target_ru_ru "Пулемётчик ССО"
   Target_uk_ua "Кулеметник ССО"
   Modified 1697852130
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{604744B067136560}" {
   Id "DRG-PLATOON_LEADER"
   Target_en_us "Platoon Leader"
   Target_ru_ru "Командир взвода"
   Target_uk_ua "Командир взводу"
   Modified 1697852270
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{60D6C02CF3A73204}" {
   Id "DRG-PlatoonLeader_SSO"
   Target_en_us "Squad Platoon Leader"
   Target_ru_ru "Командир развед-взвода"
   Target_uk_ua "Командир розвідвзводу"
   Modified 1697852381
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{60D4A950E1A5DEA1}" {
   Id "DRG-Rifleman_SSO"
   Target_en_us "Spec-Ops Operator"
   Target_ru_ru "Оперативник ССО"
   Target_uk_ua "Оперативник ССО"
   Modified 1683291846
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652ABD1FE4565C3E}" {
   Id "DRG-Rifleman_SSO_GL"
   Target_en_us "Spec-Ops Operator GL"
   Target_ru_ru "Оперативник ССО (ГП-25)"
   Target_uk_ua "Оперативник ССО (ГП-25)"
   Modified 1697303121
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652ABD12C9605732}" {
   Id "DRG-Rifleman_SSO_GM94"
   Target_en_us "Spec-Ops Operator GM94"
   Target_ru_ru "Оперативник ССО (ГМ-94)"
   Target_uk_ua "Оперативник ССО (ГМ-94)"
   Modified 1697305739
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6454F7D05B5A39E5}" {
   Id "DRG-Rifleman_SSO_RER"
   Target_en_us "Spec-Ops Radio Intelligence"
   Target_ru_ru "Оперативник ССО РЭР"
   Target_uk_ua "Оперативник ССО РЕР"
   Modified 1697852506
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{65312812140AB821}" {
   Id "DRG-Rifleman_SSO_RTO"
   Target_en_us "Spec-Ops RTO"
   Target_ru_ru "Оперативник-связист ССО"
   Target_uk_ua "Оперативник-зв’язківець ССО"
   Modified 1697852565
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{6529112CBD590F73}" {
   Id "DRG-Role-AntiTank"
   Target_en_us "Rifleman AT"
   Target_ru_ru "Гранатомётчик"
   Target_uk_ua "Гранатометник"
   Modified 1697207597
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6529112C755F13A2}" {
   Id "DRG-Role-AssistantAT"
   Target_en_us "Assistant Anti-Tank"
   Target_ru_ru "Помощник гранатомётчика"
   Target_uk_ua "Помічник гранатометника"
   Modified 1697190820
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E1DBBC868D}" {
   Id "DRG-Role-Driver"
   Target_en_us "Driver"
   Target_ru_ru "Водитель"
   Target_uk_ua "Водій"
   Modified 1683827129
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E224CBF818}" {
   Id "DRG-Role-Engineer"
   Target_en_us "Engineer"
   Target_ru_ru "Инженер"
   Target_uk_ua "Інженер"
   Modified 1683828368
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{65292AF21363AE4F}" {
   Id "DRG-Role-Flamethrower"
   Target_en_us "Flamethrower"
   Target_ru_ru "Огнемётчик"
   Target_uk_ua "Вогнеметник"
   Modified 1697852584
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64D6E60496F5ECAB}" {
   Id "DRG-Role-LeaderRebel"
   Target_en_us "Rebel TeamLeader"
   Target_ru_ru "Командир группы ополчения"
   Target_uk_ua "Командир групи ополчення"
   Modified 1691812563
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64D6E6063F14BF63}" {
   Id "DRG-Role-Milita"
   Target_en_us "Rebel"
   Target_ru_ru "Ополченец"
   Target_uk_ua "Ополченець"
   Modified 1691811174
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E0A9C7C030}" {
   Id "DRG-Role-Mortar-TL"
   Target_en_us "Mortar Crew Commander"
   Target_ru_ru "Командир миномётного расчёта"
   Target_uk_ua "Командир мінометного розрахунку"
   Modified 1697205883
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64CE753FE04B854D}" {
   Id "DRG-Role-MortarAmmoBearer"
   Target_en_us "Mortar Ammo Bearer"
   Target_ru_ru "Подносчик миномётного расчёта"
   Target_uk_ua "Піднощик мінометного розрахунку"
   Modified 1697205892
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E36B461D5A}" {
   Id "DRG-Role-MortarGunner"
   Target_en_us "Mortar Gunner"
   Target_ru_ru "Наводчик миномёта"
   Target_uk_ua "Навідник міномета"
   Modified 1697205897
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E348803A0C}" {
   Id "DRG-Role-MortarLoader"
   Target_en_us "Mortar Loader"
   Target_ru_ru "Заряжающий миномёта"
   Target_uk_ua "Заряджаючий міномета"
   Modified 1697205901
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{65113370643057FD}" {
   Id "DRG-Role-MortarSpotter"
   Target_en_us "Mortar Spotter"
   Target_ru_ru "Арт.коррективщик"
   Target_uk_ua "Арт. коригувальник"
   Modified 1697851757
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64D6E606FA027633}" {
   Id "DRG-Role-Rebel"
   Target_en_us "Rebel"
   Target_ru_ru "Ополченец"
   Target_uk_ua "Ополченець"
   Modified 1691812308
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652A716B9EBC9A34}" {
   Id "DRG-Role-ReconFlamethrower"
   Target_en_us "Recon Flamethrower"
   Target_ru_ru "Разведчик огнемётчик"
   Target_uk_ua "Развідник-вогнеметник"
   Modified 1697852610
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64F8ACC0FDF4F7E8}" {
   Id "Drg-Role-SeniorEngineer"
   Target_en_us "Senior Engineer"
   Target_ru_ru "Старший инженер"
   Target_uk_ua "Старший інженер"
   Modified 1694019164
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652AF36112DE7463}" {
   Id "DRG-Role_AirSpotter"
   Target_en_us "Air Spotter"
   Target_ru_ru "Авиакорректировщик"
   Target_uk_ua "Авіакоригувальник"
   Modified 1697849365
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61B543EF74F189EC}" {
   Id "DRG-Role_AntiTank"
   Target_en_us "Anti-Tank Specialist"
   Target_ru_ru "Гранатомётчик"
   Target_uk_ua "Гранатометник"
   Modified 1639283730
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D20F4503DA}" {
   Id "DRG-Role_AntiTankAssistant"
   Target_en_us "Anti-Tank Assistant"
   Target_ru_ru "Помощник гранатомётчика"
   Target_uk_ua "Помічник гранатометника"
   Modified 1639317917
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4FC7BD30748}" {
   Id "DRG-Role_CompanyLeader"
   Target_en_us "Company Leader"
   Target_ru_ru "Командир роты"
   Target_uk_ua "Командир роти"
   Modified 1683829399
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6529112BC5E5937A}" {
   Id "DRG-Role_CrewCommanderV"
   Target_en_us "Crew Commander"
   Target_ru_ru "Командир экипажа"
   Target_uk_ua "Командир екіпажу"
   Modified 1697193366
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D639D70EE4}" {
   Id "DRG-Role_CrewDriver"
   Target_en_us "Crew Driver"
   Target_ru_ru "Механик-водитель"
   Target_uk_ua "Механік-водій"
   Modified 1639319711
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D66CC845E4}" {
   Id "DRG-Role_CrewGunner"
   Target_en_us "Crew Gunner"
   Target_ru_ru "Наводчик-оператор"
   Target_uk_ua "Навідник-оператор"
   Modified 1697193476
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D551D4FF581}" {
   Id "DRG-Role_EngineerSapper"
   Target_en_us "Engineer Sapper"
   Target_ru_ru "Инженер сапёр"
   Target_uk_ua "Інженер-сапер"
   Modified 1639346789
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E6723A25C4}" {
   Id "DRG-Role_EngineerSeniorSapper"
   Target_en_us "Senior Engineer Sapper"
   Target_ru_ru "Старший инженер сапёр"
   Target_uk_ua "Старший інженер-сапер"
   Modified 1683826417
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652D429AC70E488C}" {
   Id "DRG-Role_Recon"
   Target_en_us "Recon"
   Target_ru_ru "Разведчик"
   Target_uk_ua "Розвідник"
   Modified 1697470690
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652EF0E0341A409F}" {
   Id "DRG-Role_Recon_AT"
   Target_en_us "Recon Anti-Tank"
   Target_ru_ru "Разведчик-гранатомётчик"
   Target_uk_ua "Розвідник-гранатометник"
   Modified 1697579120
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D47D30DA77D}" {
   Id "DRG-Role_Recon_Medic"
   Target_en_us "Scout Medic"
   Target_ru_ru "Разведчик-санитар"
   Target_uk_ua "Розвідник-санітар"
   Modified 1639353787
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B8A51EA1FA9D35}" {
   Id "DRG-Role_Recon_Officer"
   Target_en_us "Scount Officer"
   Target_ru_ru "Офицер разведки"
   Target_uk_ua "Офіцер розвідки"
   Modified 1639495009
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D59F2619D28}" {
   Id "DRG-Role_Recon_PL"
   Target_en_us "Scout Platoon Leader"
   Target_ru_ru "Командир развед.взвода"
   Target_uk_ua "Командир розвідвзводу"
   Modified 1639352821
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652EF0FA2405E4DC}" {
   Id "DRG-Role_Recon_RTO"
   Target_en_us "Recon RTO"
   Target_ru_ru "Разведчик-радист"
   Target_uk_ua "Розвідник-радист"
   Modified 1697852696
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61B66D5ADE31F74D}" {
   Id "DRG-Role_ReconAR"
   Target_en_us "Scout Automatic Rifleman"
   Target_ru_ru "Разведчик-пулемётчик"
   Target_uk_ua "Розвідник-кулеметник"
   Modified 1639352433
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D596818E85B}" {
   Id "DRG-Role_ReconAT"
   Target_en_us "Scount Aniti-Tank Specialist"
   Target_ru_ru "Разведчик-гранатомётчик"
   Target_uk_ua "Розвідник-гранатометник"
   Modified 1639352577
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B8A5135CBA7D37}" {
   Id "DRG-Role_ReconBearer"
   Target_en_us "Scout Ammo Bearer"
   Target_ru_ru "Разведчик-подносчик"
   Target_uk_ua "Розвідник-піднощик"
   Modified 1639493995
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652A901C54A4F697}" {
   Id "DRG-Role_ReconGrenadier"
   Target_en_us "Recon Grenadier"
   Target_ru_ru "Разведчик-гранатомётчик"
   Target_uk_ua "Розвідник-гранатометник"
   Modified 1699662074
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652A7167E8C9C749}" {
   Id "DRG-Role_ReconMachineGunner"
   Target_en_us "Recon Machinegunner"
   Target_ru_ru "Разведчик пулемётчик"
   Target_uk_ua "Розвідник-кулеметник"
   Modified 1697852639
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{652A901A1515E584}" {
   Id "DRG-Role_ReconRadioRI"
   Target_en_us "Intelligence Specialist RI"
   Target_ru_ru "Разведчик специалист РЭР"
   Target_uk_ua "Розвідник-спеціаліст РЕР"
   Modified 1697852657
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61B543D44D597D0A}" {
   Id "DRG-Role_ReconRifleman"
   Target_en_us "Scount Rifleman"
   Target_ru_ru "Разведчик-стрелок"
   Target_uk_ua "Розвідник-стрілець"
   Modified 1697850483
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61B66D5A52FF55AA}" {
   Id "DRG-Role_ReconRTO"
   Target_en_us "Scout RTO"
   Target_ru_ru "Разведчик-радиотелефонист"
   Target_uk_ua "Розвідник-радіотелефоніст"
   Modified 1639352186
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652A901B8A442FC1}" {
   Id "DRG-Role_ReconSapper"
   Target_en_us "Recon Sapper"
   Target_ru_ru "Разведчик-сапёр"
   Target_uk_ua "Розвідник-сапер"
   Modified 1697291741
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B613230BF7A35A}" {
   Id "DRG-Role_ReconSeniorScount"
   Target_en_us "Senior Scount"
   Target_ru_ru "Старший разведчик"
   Target_uk_ua "Старший розвідник"
   Modified 1639322535
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D5B5682B098}" {
   Id "DRG-Role_ReconSL"
   Target_en_us "Scout Leader"
   Target_ru_ru "Командир развед.группы"
   Target_uk_ua "Командир розвідгрупи"
   Modified 1639351733
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652A716F800DEB6F}" {
   Id "DRG-Role_ReconSniper"
   Target_en_us "Recon Sniper"
   Target_ru_ru "Разведчик-снайпер"
   Target_uk_ua "Розвідник-снайпер"
   Modified 1697283411
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652A716A212D3FAA}" {
   Id "DRG-Role_SeniorRecon"
   Target_en_us "Senior Recon"
   Target_ru_ru "Старший разведчик"
   Target_uk_ua "Старший розвідник"
   Modified 1697281850
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6170D2157DE458A0}" {
   Id "DRG-Role_Watchman"
   Target_en_us "Old watchman"
   Target_ru_ru "Старый сторож"
   Target_uk_ua "Старий сторож"
   Modified 1697849894
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64D364366F73B2F2}" {
   Id "DRG-Roles-RHS_Medic"
   Target_en_us "Senior Medic"
   Target_ru_ru "Санитарный инструктор"
   Target_uk_ua "Санітарний інструктор"
   Modified 1697855386
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{65290BEFFD3CE927}" {
   Id "DRG-Roles-RHS_MedicRifleman"
   Target_en_us "Medic"
   Target_ru_ru "Стрелок-санитар"
   Target_uk_ua "Стрілець-санітаp"
   Modified 1697852730
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{652CBB1EB5E53889}" {
   Id "DRG-Roles-RHS_USAF_Medic"
   Target_en_us "Medic"
   Target_ru_ru "Медик"
   Target_uk_ua "Медик"
   Modified 1697442780
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652CEBF8171FCAB9}" {
   Id "DRG-Roles_RHS_Engineer"
   Target_en_us "Engineer"
   Target_ru_ru "Инженер"
   Target_uk_ua "Інженер"
   Modified 1697449379
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED93B29CEB228}" {
   Id "DRG-Roles_RHS_Sapper"
   Target_en_us "Sapper Engineer"
   Target_ru_ru "Инженер-сапёр"
   Target_uk_ua "Інженер-сапер"
   Modified 1697920359
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61CED93A5CDD5EC9}" {
   Id "DRG-Roles_RHS_SapperLeader"
   Target_en_us "Engineering Group Commander"
   Target_ru_ru "Командир инженерной группы"
   Target_uk_ua "Командир інженерної групи"
   Modified 1697852753
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{652CEBF3ACBF087B}" {
   Id "DRG-Roles_RHS_SeniorEngineer"
   Target_en_us "Senior Engineer"
   Target_ru_ru "Старший инженер"
   Target_uk_ua "Старший інженер"
   Modified 1697446109
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652CEBF40EA8FAE6}" {
   Id "DRG-Roles_RHS_SeniorSapper"
   Target_en_us "Senior Engineering Sapper"
   Target_ru_ru "Старший инженерной-сапёр"
   Target_uk_ua "Старший сапер ісв."
   Modified 1697852929
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{6454F7818C721A31}" {
   Id "DRG-Scam-Dollars"
   Target_en_us "Scam dollars"
   Target_ru_ru "Скам доллары"
   Target_uk_ua "Скам долари"
   Modified 1697853148
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{65312817064602CF}" {
   Id "DRG-SMAW_SSO"
   Target_en_us "Spec-Ops AT-Specialist (MK-153)"
   Target_ru_ru "Оперативник ПТ Специалист"
   Target_uk_ua "Оперативник ПТ Спеціаліст"
   Modified 1697853057
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{60477B7FC9D67E7C}" {
   Id "DRG-SNIPER"
   Target_en_us "Sniper"
   Target_ru_ru "Снайпер-истребитель"
   Target_uk_ua "Снайпер-винищувач"
   Modified 1697853095
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{60D4D46322504D8F}" {
   Id "DRG-Sniper_SSO"
   Target_en_us "Spec-Ops Sniper"
   Target_ru_ru "Снайпер ССО"
   Target_uk_ua "Снайпер ССО"
   Modified 1641068534
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60477B7FF537C175}" {
   Id "DRG-SPOTTER"
   Target_en_us "Spotter"
   Target_ru_ru "Снайпер-наблюдатель"
   Target_uk_ua "Снайпер-спостерігач"
   Modified 1697853124
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{645CD4E75DF0E96F}" {
   Id "DRG-Sq-Battalion_HQ"
   Target_en_us "Battalion command"
   Target_ru_ru "Упр. батальона"
   Target_uk_ua "Управління батальйону"
   Modified 1683825973
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4FDB8B305FF}" {
   Id "DRG-Sq-CompanyHQ"
   Target_en_us "Company Headquarters"
   Target_ru_ru "Управление роты"
   Target_uk_ua "Управління роти"
   Modified 1683829323
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E260BAB97E}" {
   Id "DRG-Sq-EngineeringDetachment"
   Target_en_us "Repair detachment"
   Target_ru_ru "Ремонтное-отд."
   Target_uk_ua "Ремонтне відділення"
   Modified 1697851337
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{645CD4F6DB50E586}" {
   Id "DRG-Sq-HeliGunTransport"
   Target_en_us "Helicopter (MG)"
   Target_ru_ru "Вооруженный вертолёт"
   Target_uk_ua "Озброєний вертоліт"
   Modified 1697920751
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{645CD4F6216E0035}" {
   Id "DRG-Sq-HeliTransport"
   Target_en_us "Transport crew"
   Target_ru_ru "Транспортный вертолёт"
   Target_uk_ua "Транспортний вертоліт"
   Modified 1697849736
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{645CD4FC990D7C47}" {
   Id "DRG-Sq-MachineGunnerSquad"
   Target_en_us "Machine gunner squad"
   Target_ru_ru "Пулемётное отделение"
   Target_uk_ua "Кулеметне відділення"
   Modified 1683829801
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4FDFD85EC84}" {
   Id "DRG-Sq-MedicalTeam"
   Target_en_us "Medic Team"
   Target_ru_ru "Медицинское отделение"
   Target_uk_ua "Медичне відділення"
   Modified 1697839944
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E0F71BE16C}" {
   Id "DRG-Sq-MortarCrew"
   Target_en_us "Mortar Crew"
   Target_ru_ru "Миномётный расчёт"
   Target_uk_ua "Мінометний розрахунок"
   Modified 1697205906
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4FEB27235E3}" {
   Id "DRG-Sq-PlatoonHQ"
   Target_en_us "Platoon Headquarters"
   Target_ru_ru "Управление взвода"
   Target_uk_ua "Управління взводу"
   Modified 1683830682
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64F127C553117A4D}" {
   Id "DRG-Sq-Rebels"
   Target_en_us "Rebel Squad"
   Target_ru_ru "Отряд партизан"
   Target_uk_ua "Загін партизан"
   Modified 1697839947
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64CE7531F3425609}" {
   Id "DRG-Sq-ReconCompanyHQ"
   Target_en_us "Recon Company HQ"
   Target_ru_ru "Управление развед.роты"
   Target_uk_ua "Управління розвідроти"
   Modified 1697920777
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{645CD4F5F35E47AF}" {
   Id "DRG-Sq-ReconPlatoonHQ"
   Target_en_us "Recon Platoon HQ"
   Target_ru_ru "Управление развед.взвода"
   Target_uk_ua "Управління розвідвзводу"
   Modified 1697920773
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{645CD4F7C8444980}" {
   Id "DRG-Sq-ReconSquad"
   Target_en_us "Recon Squad"
   Target_ru_ru "Развед.отделение"
   Target_uk_ua "Розвідувальне відділення"
   Modified 1697851344
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{645CD4FA36B5C7A3}" {
   Id "DRG-Sq-RifleSquad"
   Target_en_us "Rifle Squad"
   Target_ru_ru "Стрелковое отделение"
   Target_uk_ua "Стрілецьке відділення"
   Modified 1697839953
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4F699DC84C2}" {
   Id "DRG-Sq-RocketHelicopter"
   Target_en_us "Helicopter (Rocket)"
   Target_ru_ru "Ударно-траспортный верт."
   Target_uk_ua "Ударно-транспортний верт."
   Modified 1697849722
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{645CD4E6C4179AF9}" {
   Id "DRG-Sq-SupplyTeam"
   Target_en_us "Supply team"
   Target_ru_ru "Группа снабжения"
   Target_uk_ua "Група забезпечення"
   Modified 1683826725
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E7DA63D84A}" {
   Id "DRG-Sq_DemolitionTeam"
   Target_en_us "Demolition team"
   Target_ru_ru "Сапёрное звено"
   Target_uk_ua "Саперна ланка"
   Modified 1683826225
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D4D46598F5433C}" {
   Id "DRG-Squadleader_SSO"
   Target_en_us "Spec-Ops TeamLeader"
   Target_ru_ru "Командир группы ССО"
   Target_uk_ua "Командир групи ССО"
   Modified 1697853171
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{6454F7904A5EBA4E}" {
   Id "DRG-Squadleader_SSO_Officer"
   Target_en_us "Spec-Ops Officer"
   Target_ru_ru "Офицер ССО"
   Target_uk_ua "Офіцер ССО"
   Modified 1697853175
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{6454F7928D5A7D86}" {
   Id "DRG-SR_SSO"
   Target_en_us "Spec-Ops Senior Operator"
   Target_ru_ru "Старший оперативник ССО"
   Target_uk_ua "Старший оперативник ССО"
   Modified 1683291826
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED174B131E8EA}" {
   Id "DRG-Vest_Ratnik_6B45_MG_Description"
   Target_en_us "Developed in Podval NII"
   Target_ru_ru "Разработано в НИИ Подвала \"Тактиковедении\""
   Target_uk_ua "Разроблено в НДІ Підвалу \"Тактиковедення\""
   Modified 1697853507
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61CED174D502C64A}" {
   Id "DRG-Vest_Ratnik_6B45_MG_Name"
   Target_en_us "Machinegunner vest variant (EMR)"
   Target_ru_ru "Разгрузка пулемётчика в ЕМР"
   Target_uk_ua "Розвантажка кулеметника (EMR)"
   Modified 1697853794
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61CB0A080F880E4D}" {
   Id "DRG-Weapon_NSP_Description"
   Target_en_us "Ground signal cartridge NSP, orange smoke. Used by the Soviet Army to send signals. Most often to indicate their positions in the event of friendly fire."
   Target_ru_ru "Наземный сигнальный патрон НСП, оранжевый дым. Используется Советсткой Армии для подачи сигналов. Чаще всего для обозначения своих позиций в случае дружественного огня."
   Target_uk_ua "Наземна сигнальна ракета НСП, помаранчевий дим. Використовується радянською армією для подачі сигналів, зазвичай для позначення своїх позицій у разі дружнього вогню."
   Modified 1697851285
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61CB0A082F65E9E8}" {
   Id "DRG-Weapon_NSP_Name"
   Target_en_us "NSP"
   Target_ru_ru "НСП"
   Target_uk_ua "НСП"
   Modified 1640696536
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6222CD29E41B405D}" {
   Id "DRG_ChangeFlagAction"
   Target_en_us "Change flag"
   Target_ru_ru "Поменять флаг"
   Target_uk_ua "Змінити прапор"
   Modified 1646448211
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6483160DA279A5F6}" {
   Id "DRG_DeputyPL"
   Target_en_us "Deputy platoon leader"
   Target_ru_ru "Зам. командира взвода"
   Target_uk_ua "Заступник командира взводу"
   Modified 1686317388
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{654F2E002B74E218}" {
   Id "DRG_DeputyPlatoonLeader"
   Target_en_us "Deputy Platoon Leader"
   Target_ru_ru "Зам.ком взвода"
   Modified 1699689152
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{651C6978445A8882}" {
   Id "DRG_FactionPirates"
   Target_en_us "Pirates"
   Target_ru_ru "Пираты"
   Target_uk_ua "Пірати"
   Modified 1697853812
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{651C69792F6BD7A3}" {
   Id "DRG_FactionPiratesUpper"
   Target_en_us "Confederation of Pirates"
   Target_ru_ru "Конфедерация пиратов"
   Target_uk_ua "Конфедерація піратів"
   Modified 1697853849
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{651C6975AE3CC35E}" {
   Id "DRG_FactionSmugglers"
   Target_en_us "Smugglers"
   Target_ru_ru "Контрабандисты"
   Target_uk_ua "Контрабандисти"
   Modified 1697853856
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{651B0835C9CB5A9D}" {
   Id "DRG_FlagChangeForbidden"
   Target_en_us "Change forbidden"
   Target_ru_ru "Смена флага запрещена"
   Target_uk_ua "Заміна прапора заборонена"
   Modified 1696273832
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64D476D3BB2000B9}" {
   Id "DRG_IGF"
   Target_en_us "IGF"
   Target_ru_ru "НВФ"
   Target_uk_ua "НВФ"
   Modified 1691659207
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{628699D7D2786DB1}" {
   Id "DRG_ION_PlatoonLeader"
   Target_en_us "Platoon Leader ION"
   Target_ru_ru "Главарь боевиков ION"
   Target_uk_ua "Ватажок бойовиків ION"
   Modified 1697854354
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{628699D0ECB4522C}" {
   Id "DRG_ION_RadioEng"
   Target_en_us "Radio-Specialist ION"
   Target_ru_ru "Специалист РЭР ИОН"
   Target_uk_ua "Спеціаліст РЕР ION"
   Modified 1697854379
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{628683598FD08E86}" {
   Id "DRG_ION_Rifleman"
   Target_en_us "ION Figther"
   Target_ru_ru "Боевик ИОН"
   Target_uk_ua "Бойовик ION"
   Modified 1697855106
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{6286835A8AB49ECC}" {
   Id "DRG_ION_Sapper"
   Target_en_us "Sapper ION"
   Target_ru_ru "Сапёр ИОН"
   Target_uk_ua "Сапер ION"
   Modified 1697855114
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{6286835B30D45AFD}" {
   Id "DRG_ION_TeamLeader"
   Target_en_us "TeamLeader ION"
   Target_ru_ru "Командир группы ИОН"
   Target_uk_ua "Командир групи ION"
   Modified 1697855119
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{651B0835E5136035}" {
   Id "DRG_ItsYourFlag"
   Target_en_us "Its your flag"
   Target_ru_ru "Это ваш флаг"
   Target_uk_ua "Це ваш прапор"
   Modified 1696273764
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CF39320BCCAA57}" {
   Id "DRG_PC_Gen_III_Base_AR_Desc"
   Target_en_us "Developed by Podval"
   Target_ru_ru "Разработано Институтом НИИ Подвала отдела тактикульноведения"
   Target_uk_ua "Разроблено в НДІ Підвалу \"Тактикуловедення\""
   Modified 1697855490
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61CF39323B5493D8}" {
   Id "DRG_PC_Gen_III_Base_AR_Name"
   Target_en_us "Vest for AR M249"
   Target_ru_ru "Разгрузка пулемётчика M249"
   Target_uk_ua "Розвантажка кулеметника M249"
   Modified 1697855173
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{6454F7AD451DAEA0}" {
   Id "DRG_Policeman"
   Target_en_us "Policeman"
   Target_ru_ru "Полицейский"
   Target_uk_ua "Поліцейський"
   Modified 1697855133
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64C271FB644B10C1}" {
   Id "DRG_RifleSquad"
   Target_en_us "Rifle squad"
   Target_ru_ru "Стрелковое отделение"
   Target_uk_ua "Стрілецьке відділення"
   Modified 1690464825
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{633283561F8E584A}" {
   Id "DRG_Role_AT_TeamLeader"
   Target_en_us "TeamLeader AT Squad"
   Target_ru_ru "Командир ПТ расчёта"
   Target_uk_ua "Командир ПТ розрахунку"
   Modified 1697855250
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{63328351A098CC85}" {
   Id "DRG_Role_AT_Unit"
   Target_en_us "AT Assistant"
   Target_ru_ru "Номер ПТ расчёта"
   Target_uk_ua "Номер ПТ розрахунку"
   Modified 1697855145
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{652B2B5DE93D60FC}" {
   Id "DRG_Role_Informator"
   Target_en_us "Informator"
   Target_ru_ru "Информатор"
   Target_uk_ua "Інформатор"
   Modified 1697328341
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C6912F0801D58C}" {
   Id "DRG_Role_MTO_Engineer"
   Target_en_us "Logistics Engineer"
   Target_ru_ru "Инженер МТО"
   Target_uk_ua "Інженер МТЗ"
   Modified 1697920421
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64C6912F86701E56}" {
   Id "DRG_Role_MTO_EngineerSenior"
   Target_en_us "Senior Logistics Engineer"
   Target_ru_ru "Старший инженер МТО"
   Target_uk_ua "Старший інженер МТЗ"
   Modified 1697920441
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{6328C0238BB9D206}" {
   Id "DRG_Role_TV"
   Target_en_us "Yuri Vladimirovich (TV presenter)"
   Target_ru_ru "Юрий Владимирович (Телеведущий)"
   Target_uk_ua "Юрій Володимирович (Телеведучий)"
   Modified 1663630906
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEB759F6CAB9E4}" {
   Id "DRG_Roles_RHS_AAT"
   Target_en_us "Assistant anti-tank specialist"
   Target_ru_ru "Помощник гранатомётчика"
   Target_uk_ua "Помічник гранатометника"
   Modified 1640942422
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED9311FD65658}" {
   Id "DRG_Roles_RHS_AR_RPK"
   Target_en_us "Automatic rifleman"
   Target_ru_ru "Пулемётчик РПК"
   Target_uk_ua "Кулеметник РПК"
   Modified 1697855075
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61CEB75B55D06B5E}" {
   Id "DRG_Roles_RHS_AT"
   Target_en_us "Anti-tank specialist"
   Target_ru_ru "Гранатомётчик"
   Target_uk_ua "Гранатометник"
   Modified 1640941314
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{653AED65FE4C9A28}" {
   Id "DRG_Roles_RHS_Scout_AT"
   Target_en_us "Scout Anti-Tank"
   Target_ru_ru "Разведчик ПТ"
   Modified 1698363167
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEEE215262DF68}" {
   Id "DRG_Roles_RHS_Scout_Leader"
   Target_en_us "Scout Leader"
   Target_ru_ru "Старший разведчик"
   Target_uk_ua "Старший розвідник"
   Modified 1640952603
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C271FD095BBB88}" {
   Id "DRG_Roles_RHS_Scout_REW"
   Target_en_us "Electronic intelligence specialist"
   Target_ru_ru "Специалист РЭР"
   Target_uk_ua "Спеціаліст РЕР"
   Modified 1697854403
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61CEEE211B035DE5}" {
   Id "DRG_Roles_RHS_Scout_Sapper"
   Target_en_us "Scout Sapper"
   Target_ru_ru "Разведчик-сапёр"
   Target_uk_ua "Розвідник-сапер"
   Modified 1640952698
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{653AED643DB53310}" {
   Id "DRG_Roles_RHS_ScoutMedic"
   Target_en_us "Scout Medic"
   Target_ru_ru "Разведчик-медик"
   Modified 1698363285
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEEE233B6075EA}" {
   Id "DRG_Roles_RHS_ScoutRifleman"
   Target_en_us "Scout"
   Target_ru_ru "Разведчик-стрелок"
   Target_uk_ua "Розвідник-стрілець"
   Modified 1640951470
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEEE228F0ABBB2}" {
   Id "DRG_Roles_RHS_ScoutRTO"
   Target_en_us "Scout Radio Operator"
   Target_ru_ru "Разведчик-радиотелефонист"
   Target_uk_ua "Розвідник-радіотелефоніст"
   Modified 1698361988
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{652CBB1084AC35BF}" {
   Id "Drg_Roles_SMAW_Assistant"
   Target_en_us "AT Specialist Assiastant"
   Target_ru_ru "Номер расчёта ПТ"
   Target_uk_ua "Номер розрахунку ПТ"
   Modified 1697855041
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{652CBB10BDC72C2B}" {
   Id "Drg_Roles_SMAW_Gunner"
   Target_en_us "AT Specialist Gunner"
   Target_ru_ru "Оператор-стрелок ПТ "
   Target_uk_ua "Оператор-стрілець ПТ "
   Modified 1697855059
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{60D69CE45493CFAD}" {
   Id "DRG_Sapper_SSO"
   Target_en_us "Spec-Ops Sapper"
   Target_ru_ru "Подрывник ССО"
   Target_uk_ua "Підривник ССО"
   Modified 1697854454
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{6525161AC5EB16FB}" {
   Id "DRG_Scripts_CriticalLossTitle"
   Target_en_us "Критические потери"
   Target_ru_ru "Критические потери"
   Target_uk_ua "Критичні втрати"
   Modified 1696931101
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6454F7AD163C0F5C}" {
   Id "DRG_Senior_Policeman"
   Target_en_us "Senior policeman"
   Target_ru_ru "Старший полицейский"
   Target_uk_ua "Старший поліцейський"
   Modified 1697854491
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64C271F92501C381}" {
   Id "DRG_Sqd_AT"
   Target_en_us "Anti-tank team"
   Target_ru_ru "Противотанковый расчёт"
   Target_uk_ua "Протитанковий розрахунок"
   Modified 1697854503
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64C271FBAF39752F}" {
   Id "DRG_Sqd_Engineer"
   Target_en_us "Engineer and sapper section."
   Target_ru_ru "Инженерно-сапёрная группа"
   Target_uk_ua "Інженерно-саперна група"
   Modified 1697854514
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64C69122FA312D9A}" {
   Id "DRG_Sqd_HeliRocket"
   Target_en_us "Attack helicopter crew"
   Target_ru_ru "Экипаж ударного вертолёта"
   Target_uk_ua "Екіпаж ударного вертольота"
   Modified 1697854573
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64C271FBFFF3E8F4}" {
   Id "DRG_Sqd_Hq"
   Target_en_us "Headquarter"
   Target_ru_ru "Командование"
   Target_uk_ua "Командування"
   Modified 1697854579
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64C271F937C5724C}" {
   Id "DRG_Sqd_Mg"
   Target_en_us "Machine gunner squad"
   Target_ru_ru "Пулемётное отделение"
   Target_uk_ua "Кулеметне відділення"
   Modified 1690465825
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C6912CF239D021}" {
   Id "DRG_Sqd_MTO"
   Target_en_us "Material and technical support"
   Target_ru_ru "Материально техническое обеспечение"
   Target_uk_ua "Матеріально-технічне забезпечення"
   Modified 1697854629
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64C271FA8EC6260B}" {
   Id "DRG_Sqd_PlHq"
   Target_en_us "Platoon HQ"
   Target_ru_ru "Управление взвода"
   Target_uk_ua "Управління взводу"
   Modified 1690465672
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{651AA135662F0439}" {
   Id "DRG_Sqd_RaidGroup"
   Target_en_us "Raid group"
   Target_ru_ru "Рейдовая группа"
   Target_uk_ua "Рейдовая група"
   Modified 1697854637
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64C271FB2F525D5F}" {
   Id "DRG_Sqd_Rifle"
   Target_en_us "Rifle squad"
   Target_ru_ru "Стрелковое отделение"
   Target_uk_ua "Стрілецьке відділення"
   Modified 1690464941
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C271F9DD50E11E}" {
   Id "DRG_Sqd_Snip"
   Target_en_us "Sniper team"
   Target_ru_ru "Снайперский расчёт"
   Target_uk_ua "Снайперський розрахунок"
   Modified 1697854778
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{64C271FB955327D2}" {
   Id "DRG_Sqd_SSO"
   Target_en_us "Sabotage group"
   Target_ru_ru "Диверсионная группа"
   Target_uk_ua "Диверсійна група"
   Modified 1697854665
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{62868352D24FB61B}" {
   Id "DRG_SS_rifleman"
   Target_en_us "Security service officer"
   Target_ru_ru "Оперативник службы безопасности"
   Target_uk_ua "Оперативник служби безпеки"
   Modified 1697854416
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61D2C04C20454E0C}" {
   Id "DRG_TKR_Roles_AT"
   Target_en_us "Rebel AT"
   Target_ru_ru "Боевик гранатомётчик"
   Target_uk_ua "Бойовик гранатометник"
   Modified 1697854814
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61D2C04B3C2294F6}" {
   Id "DRG_TKR_Roles_CL"
   Target_en_us "Rebel Leader"
   Target_ru_ru "Главарь боевиков"
   Target_uk_ua "Ватажок бойовиків"
   Modified 1697854830
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61D2C04D0433B923}" {
   Id "DRG_TKR_Roles_MachineGunner"
   Target_en_us "Rebel Machinegunner"
   Target_ru_ru "Боевик пулемётчик"
   Target_uk_ua "Бойовик кулеметник"
   Modified 1697854839
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{651C7E69AEB48499}" {
   Id "DRG_TKR_Roles_MortarLeader"
   Target_en_us "Rebel Mortar Leader"
   Target_ru_ru "Боевик командир миномёта"
   Target_uk_ua "Бойовик командир міномета"
   Modified 1697855288
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{651CC5C60E2E3205}" {
   Id "DRG_TKR_Roles_MortarLoader"
   Target_en_us "Rebel Mortar Loader"
   Target_ru_ru "Боевик заряжающий"
   Target_uk_ua "Бойовик заряджаючий"
   Modified 1697854858
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{651C7E6A0A99BA32}" {
   Id "DRG_TKR_Roles_Mortarman"
   Target_en_us "Rebel Mortarman"
   Target_ru_ru "Боевик миномётчик"
   Target_uk_ua "Бойовик мінометник"
   Modified 1697854884
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{651CC5C7B26819D3}" {
   Id "DRG_TKR_Roles_MortarSpotter"
   Target_en_us "Rebel Mortal Spotter"
   Target_ru_ru "Боевик арт-корректирощик"
   Target_uk_ua "Бойовик арт.корегувальник"
   Modified 1697854875
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61D2C04C88E60C22}" {
   Id "DRG_TKR_Roles_PL"
   Target_en_us "Rebel Platoon Leader"
   Target_ru_ru "Командир боевой ячейки"
   Target_uk_ua "Командир бойової групи"
   Modified 1697854919
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61D2C0510CDBBC88}" {
   Id "DRG_TKR_Roles_Rifleman"
   Target_en_us "Rebel"
   Target_ru_ru "Боевик"
   Target_uk_ua "Бойовик"
   Modified 1697854927
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61D2EE9512C4CDEE}" {
   Id "DRG_TKR_Roles_Sapper"
   Target_en_us "Rebel sapper"
   Target_ru_ru "Боевик подрывник"
   Target_uk_ua "Бойовик підривник"
   Modified 1697854997
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61D2C0506FA5D411}" {
   Id "DRG_TKR_Roles_SL"
   Target_en_us "Rebel Squad Leader"
   Target_ru_ru "Командир отряда боевиков"
   Target_uk_ua "Командир загіну бойовиків"
   Modified 1697854989
   Author "hasta"
   LastChanged "rezni"
  }
  CustomStringTableItem "{61D2C051A78E14B7}" {
   Id "DRG_TKR_Roles_TL"
   Target_en_us "Rebel Team Leader"
   Target_ru_ru "Опытный боевик"
   Target_uk_ua "Досвідчений бойовик"
   Modified 1697855022
   Author "hasta"
   LastChanged "rezni"
  }
 }
}