SCR_MissionHeader {
 World "{30C924BF5419B8F8}Worlds/mTSG_Tyn_Half_of_War_Gogland/mTSG_Tyn_Half_of_War_Gogland.ent"
 m_sName "Половина войны"
 m_sAuthor "Tynec"
 m_sDescription "Требуемые аддоны: RHS - Status Quo, British Forces, Usable ballistic shield, Tactical Flava"
 m_sIcon "{E188A17B88D252DB}UI/Textures/MissionLoadingScreens/LoadingScreenSurvival.edds"
 m_sLoadingScreen "{E188A17B88D252DB}UI/Textures/MissionLoadingScreens/LoadingScreenSurvival.edds"
 m_sPreviewImage "{E188A17B88D252DB}UI/Textures/MissionLoadingScreens/LoadingScreenSurvival.edds"
 m_sGameMode "mTSG"
 m_iPlayerCount 56
}