SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{663515AA09422143}" {
   m_Info SCR_UIInfo "{663515AA6CDC064B}" {
    Name "Боевики"
    Icon "{6A33922D2B950A7A}UI/Textures/Editor/EditableEntities/Factions/RNRF_Icon.edds"
   }
   m_LabelType FACTION_Tyn_RNRF
   m_LabelGroupType FACTION
  }
 }
}