SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{66292A4E0ECBEBA3}" {
   m_Info SCR_UIInfo "{66292A4E06DF9246}" {
    Name "#TYN-Faction_RNRF"
    Icon "{6A33922D2B950A7A}UI/Textures/Editor/EditableEntities/Factions/RNRF_Icon.edds"
   }
   m_LabelType FACTION_Tyn_RNRF
   m_LabelGroupType FACTION
  }
 }
}