SCR_MissionHeader {
 World "{CC1E3CB2609AB8E8}Worlds/mTSG_Tyn_EveryoneLiar_Takistan/mTSG_Tyn_EveryoneLiar_Takistan.ent"
 m_sName "Одни Лжецы"
 m_sAuthor "Tynec"
 m_sDescription "Зависимость: TacticalFlava, MiddleEastInsurgents, BigChungusRifles, BigChungusLMGs, BigChungusSMGs, BigChungusBoltGun"
 m_sIcon "{EB78D30911B8548C}UI/Textures/MissionLoadingScreens/Reforger_HQCArt_Arland_UI.edds"
 m_sLoadingScreen "{EB78D30911B8548C}UI/Textures/MissionLoadingScreens/Reforger_HQCArt_Arland_UI.edds"
 m_sPreviewImage "{EB78D30911B8548C}UI/Textures/MissionLoadingScreens/Reforger_HQCArt_Arland_UI.edds"
 m_sGameMode "mTSG"
 m_iPlayerCount 53
 m_iStartingHours 12
}