SCR_MissionHeader {
 World "{13DDB681A12EDE8B}Worlds/mTSG_Glin_Operation_Buratino_Gogland/mTSG_Glin_Operation_Buratino_Gogland.ent"
 m_sName "Операция Буратино"
 m_sAuthor "Glinopolk"
 m_sDescription "Требуемы аддоны: RHS - Status Quo, Arma 2 Factions"
 m_sIcon "{E188A17B88D252DB}UI/Textures/MissionLoadingScreens/LoadingScreenSurvival.edds"
 m_sLoadingScreen "{E188A17B88D252DB}UI/Textures/MissionLoadingScreens/LoadingScreenSurvival.edds"
 m_sPreviewImage "{E188A17B88D252DB}UI/Textures/MissionLoadingScreens/LoadingScreenSurvival.edds"
 m_sGameMode "mTSG"
 m_iPlayerCount 62
 m_bOverrideScenarioTimeAndWeather 1
 m_iStartingHours 12
}